"""Analyze completed blinded labels without changing the frozen main sample."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd


VALID_LABELS = {"yes", "no", "uncertain"}
BOOTSTRAP_DRAWS = 2_000
BOOTSTRAP_SEED = 20260903


def percent(value: float) -> str:
    return f"{100 * value:.1f}"


def write_generated_results(path: Path | None, result: dict[str, object]) -> None:
    if path is None:
        return
    education = result["education_rule"]
    dependency = result["dependency_edge_rule"]
    service = result["service_negative_audit"]
    education_status = result["education_relevance"]
    dependency_status = result["dependency_evidence"]
    service_status = result["service_negative_audit"]
    commands = {
        "EducationValidationN": education_status["records"],
        "EducationValidationAgreement": percent(
            education_status["initial_interreviewer_agreement"]["agreement"]
        ),
        "EducationValidationKappa": f"{education_status['initial_interreviewer_agreement']['kappa']:.3f}",
        "EducationValidationPrecision": percent(education["precision"]),
        "EducationValidationPrecisionLow": percent(
            education["bootstrap_intervals"]["precision"][0]
        ),
        "EducationValidationPrecisionHigh": percent(
            education["bootstrap_intervals"]["precision"][1]
        ),
        "EducationValidationRecall": percent(education["recall_within_query_union"]),
        "EducationValidationRecallLow": percent(
            education["bootstrap_intervals"]["recall_within_query_union"][0]
        ),
        "EducationValidationRecallHigh": percent(
            education["bootstrap_intervals"]["recall_within_query_union"][1]
        ),
        "EducationValidationSpecificity": percent(
            education["specificity_within_query_union"]
        ),
        "DependencyValidationN": dependency_status["records"],
        "DependencyValidationAgreement": percent(
            dependency_status["initial_interreviewer_agreement"]["agreement"]
        ),
        "DependencyValidationKappa": f"{dependency_status['initial_interreviewer_agreement']['kappa']:.3f}",
        "DependencyValidationPrecision": percent(dependency["precision_overall"]),
        "DependencyValidationPrecisionLow": percent(
            dependency["bootstrap_intervals"]["precision_overall"][0]
        ),
        "DependencyValidationPrecisionHigh": percent(
            dependency["bootstrap_intervals"]["precision_overall"][1]
        ),
        "ServiceNegativeValidationN": service_status["records"],
        "ServiceNegativeValidationAgreement": percent(
            service_status["initial_interreviewer_agreement"]["agreement"]
        ),
        "ServiceNegativeValidationKappa": f"{service_status['initial_interreviewer_agreement']['kappa']:.3f}",
        "ServiceMissedN": service["missed_service_records"],
        "ServiceMissedShare": percent(service["missed_service_share"]),
        "ServiceMissedShareLow": percent(
            service["bootstrap_intervals"]["missed_service_share"][0]
        ),
        "ServiceMissedShareHigh": percent(
            service["bootstrap_intervals"]["missed_service_share"][1]
        ),
        "ServiceMissedCandidateN": service[
            "missed_service_records_in_candidate_boundary"
        ],
    }
    lines = [
        "% Generated by pilot/src/analyze_validation_labels.py; do not edit manually."
    ]
    lines.extend(
        rf"\newcommand{{\{name}}}{{{value}}}" for name, value in commands.items()
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def normalized_label(value: object) -> str:
    label = str(value or "").strip().casefold()
    return label if label in VALID_LABELS else ""


def resolved_label(reviewer1: object, reviewer2: object, adjudicated: object) -> str:
    first = normalized_label(reviewer1)
    second = normalized_label(reviewer2)
    final = normalized_label(adjudicated)
    if first in {"yes", "no"} and first == second:
        return first
    if final in {"yes", "no"}:
        return final
    return ""


def cohen_kappa(first: pd.Series, second: pd.Series) -> dict[str, float | int | None]:
    pairs = pd.DataFrame(
        {
            "first": first.map(normalized_label),
            "second": second.map(normalized_label),
        }
    )
    pairs = pairs[pairs["first"].isin(VALID_LABELS) & pairs["second"].isin(VALID_LABELS)]
    if pairs.empty:
        return {"n": 0, "agreement": None, "kappa": None}
    labels = sorted(VALID_LABELS)
    agreement = float(pairs["first"].eq(pairs["second"]).mean())
    expected = sum(
        float(pairs["first"].eq(label).mean())
        * float(pairs["second"].eq(label).mean())
        for label in labels
    )
    kappa = (agreement - expected) / (1 - expected) if expected < 1 else 1.0
    return {"n": len(pairs), "agreement": agreement, "kappa": float(kappa)}


def ratio(numerator: float, denominator: float) -> float | None:
    return numerator / denominator if denominator > 0 else None


def education_metrics(frame: pd.DataFrame) -> dict[str, float | None]:
    weight = 1.0 / frame["inclusion_probability"].astype(float)
    human = frame["resolved"].eq("yes")
    automatic = frame["education_strict_match"].fillna(False).astype(bool)
    tp = float(weight[human & automatic].sum())
    fp = float(weight[~human & automatic].sum())
    fn = float(weight[human & ~automatic].sum())
    tn = float(weight[~human & ~automatic].sum())
    return {
        "precision": ratio(tp, tp + fp),
        "recall_within_query_union": ratio(tp, tp + fn),
        "specificity_within_query_union": ratio(tn, tn + fp),
        "weighted_true_positive": tp,
        "weighted_false_positive": fp,
        "weighted_false_negative": fn,
        "weighted_true_negative": tn,
    }


def stratified_bootstrap(
    frame: pd.DataFrame,
    metric,
    *,
    draws: int = BOOTSTRAP_DRAWS,
    seed: int = BOOTSTRAP_SEED,
) -> dict[str, list[float]]:
    rng = np.random.default_rng(seed)
    values: dict[str, list[float]] = {}
    groups = [group.reset_index(drop=True) for _, group in frame.groupby("validation_stratum")]
    for _ in range(draws):
        sampled = pd.concat(
            [
                group.iloc[rng.integers(0, len(group), size=len(group))]
                for group in groups
            ],
            ignore_index=True,
        )
        result = metric(sampled)
        for name, value in result.items():
            if value is not None and name in {
                "precision",
                "recall_within_query_union",
                "specificity_within_query_union",
                "precision_overall",
                "missed_service_share",
            }:
                values.setdefault(name, []).append(float(value))
    return {
        name: [float(np.quantile(series, 0.025)), float(np.quantile(series, 0.975))]
        for name, series in values.items()
    }


def positive_precision(frame: pd.DataFrame) -> dict[str, float | None]:
    weight = 1.0 / frame["inclusion_probability"].astype(float)
    supported = frame["resolved"].eq("yes")
    return {"precision_overall": ratio(float(weight[supported].sum()), float(weight.sum()))}


def missed_service(frame: pd.DataFrame) -> dict[str, float | None]:
    weight = 1.0 / frame["inclusion_probability"].astype(float)
    missed = frame["resolved"].eq("yes")
    return {"missed_service_share": ratio(float(weight[missed].sum()), float(weight.sum()))}


def task_status(
    frame: pd.DataFrame,
    first: str,
    second: str,
    adjudicated: str,
) -> tuple[pd.DataFrame, dict[str, object]]:
    labeled = frame.copy()
    labeled["resolved"] = labeled.apply(
        lambda row: resolved_label(row[first], row[second], row[adjudicated]), axis=1
    )
    agreement = cohen_kappa(labeled[first], labeled[second])
    unresolved = int(labeled["resolved"].eq("").sum())
    return labeled, {
        "records": len(labeled),
        "resolved_records": len(labeled) - unresolved,
        "unresolved_records": unresolved,
        "initial_interreviewer_agreement": agreement,
    }


def analyze(root: Path, *, write_tex: bool = False) -> dict[str, object]:
    source = root / "data/validation_private"
    results = root / "analysis_results"
    qa = root / "data/qa"

    education_blind = pd.read_csv(source / "education_relevance_blinded.csv", keep_default_na=False)
    education_key = pd.read_csv(source / "education_relevance_key.csv")
    dependency_blind = pd.read_csv(source / "dependency_evidence_blinded.csv", keep_default_na=False)
    dependency_key = pd.read_csv(source / "dependency_evidence_key.csv")
    negative_blind = pd.read_csv(source / "service_negative_blinded.csv", keep_default_na=False)
    negative_key = pd.read_csv(source / "service_negative_key.csv")

    education, education_status = task_status(
        education_blind.merge(education_key, on="sample_id", validate="one_to_one"),
        "reviewer1_education_relevant",
        "reviewer2_education_relevant",
        "adjudicated_education_relevant",
    )
    dependency, dependency_status = task_status(
        dependency_blind.merge(dependency_key, on="sample_id", validate="one_to_one"),
        "reviewer1_dependency_supported",
        "reviewer2_dependency_supported",
        "adjudicated_dependency_supported",
    )
    negative, negative_status = task_status(
        negative_blind.merge(negative_key, on="sample_id", validate="one_to_one"),
        "reviewer1_named_service_present",
        "reviewer2_named_service_present",
        "adjudicated_named_service_present",
    )
    pending = any(
        status["unresolved_records"] > 0
        for status in (education_status, dependency_status, negative_status)
    )
    status_report: dict[str, object] = {
        "status": "PENDING" if pending else "COMPLETE",
        "labels_do_not_change_frozen_analysis": True,
        "education_relevance": education_status,
        "dependency_evidence": dependency_status,
        "service_negative_audit": negative_status,
    }
    (qa / "measurement_validation_status.json").write_text(
        json.dumps(status_report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    if pending:
        return status_report

    education_result = education_metrics(education)
    education_result["bootstrap_intervals"] = stratified_bootstrap(
        education, education_metrics
    )
    dependency_result = positive_precision(dependency)
    dependency_result["supported_records"] = int(dependency["resolved"].eq("yes").sum())
    dependency_result["bootstrap_intervals"] = stratified_bootstrap(
        dependency, positive_precision
    )
    negative_result = missed_service(negative)
    missed_space_ids = set(
        negative.loc[negative["resolved"].eq("yes"), "space_id"].astype(str)
    )
    candidate_path = qa / "unmapped_dependency_candidates.csv"
    candidate_space_ids = set(
        pd.read_csv(candidate_path, keep_default_na=False)["space_id"].astype(str)
    )
    negative_result["missed_service_records"] = len(missed_space_ids)
    negative_result["missed_service_records_in_candidate_boundary"] = len(
        missed_space_ids & candidate_space_ids
    )
    negative_result["all_missed_service_projects_in_candidate_boundary"] = (
        missed_space_ids <= candidate_space_ids
    )
    negative_result["bootstrap_intervals"] = stratified_bootstrap(
        negative, missed_service
    )
    result: dict[str, object] = {
        **status_report,
        "bootstrap_draws": BOOTSTRAP_DRAWS,
        "bootstrap_seed": BOOTSTRAP_SEED,
        "education_rule": education_result,
        "dependency_edge_rule": dependency_result,
        "service_negative_audit": {**negative_status, **negative_result},
        "interpretation": (
            "post-analysis measurement validation; labels evaluate but do not "
            "adjudicate the frozen sample or dependency edges"
        ),
    }
    (results / "measurement_validation.json").write_text(
        json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    write_generated_results(
        root.parent / "paper" / "generated_validation_results.tex"
        if write_tex
        else None,
        result,
    )

    rows: list[dict[str, object]] = []
    for task, frame in (
        ("education_relevance", education),
        ("dependency_evidence", dependency),
        ("service_negative", negative),
    ):
        for stratum, group in frame.groupby("validation_stratum"):
            rows.append(
                {
                    "task": task,
                    "stratum": stratum,
                    "sample_n": len(group),
                    "resolved_yes": int(group["resolved"].eq("yes").sum()),
                    "resolved_no": int(group["resolved"].eq("no").sum()),
                }
            )
    pd.DataFrame(rows).to_csv(results / "measurement_validation_by_stratum.csv", index=False)

    deidentified: list[pd.DataFrame] = []
    for task, frame, first, second, adjudicated, automatic in (
        (
            "education_relevance",
            education,
            "reviewer1_education_relevant",
            "reviewer2_education_relevant",
            "adjudicated_education_relevant",
            education["education_strict_match"].fillna(False).astype(bool),
        ),
        (
            "dependency_evidence",
            dependency,
            "reviewer1_dependency_supported",
            "reviewer2_dependency_supported",
            "adjudicated_dependency_supported",
            pd.Series(True, index=dependency.index),
        ),
        (
            "service_negative",
            negative,
            "reviewer1_named_service_present",
            "reviewer2_named_service_present",
            "adjudicated_named_service_present",
            pd.Series(False, index=negative.index),
        ),
    ):
        public_frame = pd.DataFrame(
            {
                "task": task,
                "sample_id": frame["sample_id"],
                "validation_stratum": frame["validation_stratum"],
                "inclusion_probability": frame["inclusion_probability"],
                "automatic_positive": automatic,
                "reviewer1_label": frame[first].map(normalized_label),
                "reviewer2_label": frame[second].map(normalized_label),
                "third_review_label": frame[adjudicated].map(normalized_label),
                "resolved_label": frame["resolved"],
            }
        )
        public_frame["candidate_boundary"] = (
            frame["space_id"].astype(str).isin(candidate_space_ids)
            if task == "service_negative"
            else pd.Series(pd.NA, index=frame.index, dtype="boolean")
        )
        deidentified.append(public_frame)
    pd.concat(deidentified, ignore_index=True).to_csv(
        results / "measurement_validation_deidentified.csv", index=False
    )
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument(
        "--write-tex",
        action="store_true",
        help="also write the legacy generated-validation TeX macro file",
    )
    args = parser.parse_args()
    print(
        json.dumps(
            analyze(args.root.resolve(), write_tex=args.write_tex),
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
